### ISSUE TITLE
Force-trigger a GC pass

### ISSUE THREAD

**Issue by arcanis** [pebal/sgcl#4]
It'd be useful for testing purposes to have a way to trigger a forced synchronous GC pass, and get back the amount of objects that the collector managed to release.

**Comment by pebal** [comment]
I'm sorry it took so long, but I had to change the code structure and fix some errors.

I added the `collector::force_collect()` method with an optional parameter to wait for the cycle to complete. 
I also added the `collector::live_object_count()` method that returns the current number of live objects.

**Comment by pebal** [comment]
I also added the collector::live_objects() method, which allows you to get a list of live objects.
